name: apple
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - pyyaml
  - pip:
      - --index-url https://download.pytorch.org/whl/cpu
      - torch
